{"level":"ERROR","location":"[get_call:145] fyersModel","message":{"API":"/history","Error":{"code":-16,"message":"Could not authenticate the user","s":"error"}},"timestamp":"2025-03-19 14:02:30,433+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:145] fyersModel","message":{"API":"/history","Error":{"code":-16,"message":"Could not authenticate the user","s":"error"}},"timestamp":"2025-03-19 14:02:32,933+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:145] fyersModel","message":{"API":"/history","Error":{"code":-16,"message":"Could not authenticate the user","s":"error"}},"timestamp":"2025-03-19 14:02:35,275+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:145] fyersModel","message":{"API":"/history","Error":{"code":-16,"message":"Could not authenticate the user","s":"error"}},"timestamp":"2025-03-19 14:02:37,578+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:145] fyersModel","message":{"API":"/history","Error":{"code":-16,"message":"Could not authenticate the user","s":"error"}},"timestamp":"2025-03-19 14:02:39,894+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:145] fyersModel","message":{"API":"/history","Error":{"code":-16,"message":"Could not authenticate the user","s":"error"}},"timestamp":"2025-03-19 14:02:42,215+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:145] fyersModel","message":{"API":"/history","Error":{"code":-16,"message":"Could not authenticate the user","s":"error"}},"timestamp":"2025-03-19 14:02:44,615+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:145] fyersModel","message":{"API":"/history","Error":{"code":-16,"message":"Could not authenticate the user","s":"error"}},"timestamp":"2025-03-19 14:02:47,419+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:145] fyersModel","message":{"API":"/history","Error":{"code":-16,"message":"Could not authenticate the user","s":"error"}},"timestamp":"2025-03-19 14:02:49,787+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:145] fyersModel","message":{"API":"/history","Error":{"code":-16,"message":"Could not authenticate the user","s":"error"}},"timestamp":"2025-03-19 14:02:52,121+0530","service":"FyersAPI"}
